stages:
  - build
  - test
job:
  stage: build
  script:
  - echo "Restoring NuGet Packages..."
  - D:\Programs\NuGet\nuget.exe restore "KNNClassifier.sln"
  - ''
  - echo "Release build..."
  - '"C:\Program Files\MSBuild\14.0\Bin\msbuild.exe" /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "KNNClassifier.sln"'

test:
  stage: test
  script:
  - echo "starting tests"
  - cd %PROJECT_NAME%Tests/bin/Release
  - '"D:\Programs\Visual Studio 2015 Community\Common7\IDE\MSTest.exe" /testcontainer:%PROJECT_NAME%Tests.dll'
  dependencies:
  - build